### ISSUE TITLE
Cập nhật lại prompt theo template mới nhất

### ISSUE THREAD

**Issue by tienthegainz** [vinhyenvodoi98/LLM_hackathon_2023#29]
- Sửa lại prompt phần phân tích template theo như cập nhật template mới nhất tại #28
- Cập nhật lại backend/llm/config/prompt_config.py sau khi đã sửa xong ==> Nhi làm trong https://github.com/vinhyenvodoi98/LLM_hackathon_2023/issues/27

**Comment by dduong166** [comment]
prompt mới: https://docs.google.com/document/d/10X-5_qZ9n-BpH3SXC5BfXcrVzaexwHwtsANyYV8gzck/edit
